name: Build & Deploy AlutaMart

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-deploy:
    name: Build, Test, and Deploy AlutaMart

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.300'

      - name: Build and Publish
        run: |
          dotnet restore AlutaMartAPI/AlutaMartAPI.csproj
          dotnet build --configuration Release --no-restore AlutaMartAPI/AlutaMartAPI.csproj
          dotnet publish -c Release -o ./publish AlutaMartAPI/AlutaMartAPI.csproj
